package interfaces.enums;

public enum ConversationIDs {
    ASK_PROPOSALS,
    ASK_COMPANY_PROPOSALS,
    ACCEPT_THESIS_PROPOSAL,
    INFORM_THESIS_COMMITTEE,
    SELECT_SUPERVISOR_FOR_EXTERNAL_THESIS,
    PROPOSE_ADHOC_THESIS_TO_SUPERVISOR
}
