package interfaces.enums;

public enum ConversationIDs {
    ASK_PROPOSALS,
    ASK_COMPANY_PROPOSALS,
    ACCEPT_THESIS_PROPOSAL,
    INFORM_THESIS_COMMITTEE_FOR_ONGOING_THESIS_REGISTRATION,
    INFORM_THESIS_COMMITTEE_FOR_EXTERNAL_THESIS,
    SELECT_SUPERVISOR_FOR_EXTERNAL_THESIS,
    PROPOSE_ADHOC_THESIS_TO_SUPERVISOR,
    THESIS_ALREADY_BEEN_PICKED,
}
