package interfaces.enums;

public enum ConversationIDs {
    ASK_PROPOSALS,
    ASK_COMPANY_PROPOSALS,
    ACCEPT_THESIS_PROPOSAL,
    ACCEPT_COMPANY_THESIS_PROPOSAL,
    INFORM_STUDENT_CAN_START_COMPANY_THESIS,
    INFORM_THESIS_COMMITTEE_FOR_ONGOING_THESIS_REGISTRATION,
    INFORM_THESIS_COMMITTEE_FOR_EXTERNAL_THESIS,
    SELECT_SUPERVISOR_FOR_EXTERNAL_THESIS,
    PROPOSE_ADHOC_THESIS_TO_SUPERVISOR,
    THESIS_ALREADY_BEEN_PICKED,
    REJECT_PROPOSAL_IF_NOT_INTERESTED,
    REJECT_COMPANY_PROPOSAL_IF_NOT_INTERESTED,
    ASSIGN_REVIEWER_FOR_THESIS,
    WHO_IS_YOUR_THESIS_REVIEWER
}
