package interfaces.enums;

public enum ProfessorMessageContents {
    OFFER_THESIS_PROPOSALS,
    AD_HOC_THESIS_PROPOSAL_ACCEPTED,
    AD_HOC_THESIS_PROPOSAL_REJECTED,
    EXTERNAL_THESIS_PROPOSAL_REJECTED,
    REVIEWER_REVISED_THE_THESIS,
    REVIEWER_INFORMS_THE_COMMITTEE_ABOUT_MEETING_THE_STUDENT,
    THCOMMITTEE_CONFIRMS_THE_MEETING_BETWEEN_REVIEWER_AND_STUDENT

    }
