package interfaces.enums;

public enum StudentMessageContents {

    REQUEST_ALL_THESIS_PROPOSALS,
    REQUEST_COMPANY_THESIS_PROPOSALS,
    REJECT_EXTERNAL_THESIS_PROPOSAL,
    FIRST_CONNECTION_WITH_REVIEWER
}
