package interfaces;

public interface ProfessorMessageContents {
    String OFFER_THESIS_PROPOSALS = "OFFER_THESIS_PROPOSALS";
    String AD_HOC_THESIS_PROPOSAL_ACCEPTED = "AD_HOC_THESIS_PROPOSAL_ACCEPTED";
    String AD_HOC_THESIS_PROPOSAL_REJECTED = "AD_HOC_THESIS_PROPOSAL_REJECTED";
    String EXTERNAL_THESIS_PROPOSAL_REJECTED = "EXTERNAL_THESIS_PROPOSAL_REJECTED";
    String REVIEWER_REVISED_THE_THESIS = "REVIEWER_REVISED_THE_THESIS";
    String REVIEWER_INFORMS_THE_COMMITTEE_ABOUT_MEETING_THE_STUDENT = "REVIEWER_INFORMS_THE_COMMITTEE_ABOUT_MEETING_THE_STUDENT";
}
