package interfaces;


public interface StudentMessageContents {
    String REQUEST_ALL_THESIS_PROPOSALS = "REQUEST_ALL_THESIS_PROPOSALS";
    String REQUEST_COMPANY_THESIS_PROPOSALS = "REQUEST_COMPANY_THESIS_PROPOSALS";
    String REJECT_EXTERNAL_THESIS_PROPOSAL = "REJECT_EXTERNAL_THESIS_PROPOSAL";

    String FIRST_CONNECTION_WITH_REVIEVER = "FIRST_CONNECTION_WITH_REVIEVER";
}
