package interfaces;


public interface StudentMessageContents {
    String REQUEST_ALL_THESIS_PROPOSALS = "REQUEST_ALL_THESIS_PROPOSALS";
    String REQUEST_COMPANY_THESIS_PROPOSALS = "REQUEST_COMPANY_THESIS_PROPOSALS";
}
