package interfaces;

public interface SupervisorMessageContents {
    String OFFER_THESIS_PROPOSALS = "OFFER_THESIS_PROPOSALS";
    String AD_HOC_THESIS_PROPOSAL_ACCEPTED = "AD_HOC_THESIS_PROPOSAL_ACCEPTED";
    String AD_HOC_THESIS_PROPOSAL_REJECTED = "AD_HOC_THESIS_PROPOSAL_REJECTED";
}
